### ISSUE TITLE
HttpException isn't deserialized correctly

### ISSUE THREAD

**Issue by tozaicevas** [tozaicevas/epicenter#32]
In FaceAPIService, when you get HttpException (326 line), the exception is not deserialized correctly, it's just null.

**Comment by zigsas** [comment]
Fixed it. HttpException had to have a single property of the type "Error". Created a new struct named "Error" and moved properties that previously were in HttpException to Error.

**Comment by tozaicevas** [comment]
OK, where's the fix? 🗡

**Comment by zigsas** [comment]
Just created a pull request.

**Comment by zigsas** [comment]
Nvm, it's in fix-architecture branch.
